language: php

php:
  - '7.4'

jobs:
  allow_failures:
    - php: nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: vendor/phpunit/phpunit/phpunit tests/
